language: scala
group: travis_lts
scala:
  - 2.13.1

addons:
  apt:
    update: true

script:
  - sbt clean test
  - sbt dependencyUpdates
after_success:
  - sbt coveralls

cache:
  directories:
    - $HOME/.sbt
