language: scala
group: travis_lts
scala:
  - 2.12.6
jdk: oraclejdk8

addons:
  apt:
    update: true

jdk:
  - oraclejdk8

script:
  - sbt ";clean ;assembly"
  - spring-scala/gradlew clean build -b spring-scala/build.gradle

cache:
  directories:
    - $HOME/.gradle

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 551ffd9e-aac2-4eff-937c-d8bcca72bf38
