language: scala
group: travis_lts
scala:
  - 2.12.6
jdk: oraclejdk8

addons:
  apt:
    update: true

jdk:
  - oraclejdk8

script:
  - sbt ";clean ;coverage ;assembly ;coverageReport"
  - spring-scala/gradlew clean build -b spring-scala/build.gradle

cache:
  directories:
    - $HOME/.gradle
