language: scala
group: travis_lts
scala:
  - 2.12.8

addons:
  apt:
    update: true

script:
  - sbt ";clean ;coverage ;test ;coverageReport ;coverageAggregate"
  - sbt dependencyUpdates
after_success:
  - sbt coveralls

cache:
  directories:
    - $HOME/.sbt
