language: scala
group: travis_lts
scala:
  - 2.12.7
jdk: oraclejdk8

addons:
  apt:
    update: true

jdk:
  - oraclejdk11

script:
  - sbt ";clean ;coverage ;assembly ;coverageReport"
  - sbt coverageAggregate
after_success:
  - sbt coveralls

cache:
  directories:
    - $HOME/.gradle
