addSbtPlugin("com.eed3si9n"   % "sbt-assembly"           % "2.0.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"           % "2.4.6")
addSbtPlugin("org.scoverage"  % "sbt-coveralls"          % "1.3.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"          % "2.0.6")
addSbtPlugin("ch.epfl.scala"  % "sbt-bloop"              % "1.5.4-14-7cb43276")
addSbtPlugin("com.github.sbt" % "sbt-native-packager"    % "1.9.11")
addSbtPlugin("org.jmotor.sbt" % "sbt-dependency-updates" % "1.2.7")
