= Dependency Analyzer
Carlos Martin Garcia
:toc: left
:toclevels: 4
:icons: font
:sectnums:
:tabsize: 4
:docinfo1:
:source-highlighter: prettify

== Estudio

Obtener dependencias mediante comandos bash

 gw dep | \
 grep -e '([0-9a-z\.-]*):([a-z-]*):([a-zA-Z0-9\.-]*)' | \
 sed 's/[+\]---//g; s/|//g' | \
 awk '{print $1}' | \
 sort -u

Regex

([0-9a-z.]+):([0-9a-z-]+):([0-9.]+)?.*
 
http://queirozf.com/entries/scala-regular-expressions-examples-reference

 https://logback.qos.ch/manual/configuration.html

Obtener dependencias y generar un archivo

 gw dep --configuration default > /tmp/gradle-deps-default


Lista de tareas previas al caso de uso:

- sbt dependencyList > sbt-dependencies.log

- regex para filtrar líneas con deps: ^[a-z]([a-z0-9-_\.]+:){2}([0-9A-Z-\.]+)

- log con los positivos y negativos para verificar si la regex filtra correctamente

- split del GAV por el caracter ":" (dos puntos)

- añadir las deps a un Set para eliminar duplicados

- obtener del repository todas las dependencias para el par (G,A)

- obtener la última versión

- consultar con maven central para verificar si ha cambiado

- elaborar el report con las dependencias que tienen nueva versión

== Links

- ZIO Error Management: https://www.youtube.com/watch?v=mGxcaQs3JWI
- Functional Concurrency in Scala with ZIO: https://www.youtube.com/watch?v=m5nas4Hndqo&t=
