name: Scala CI

on: [push]

jobs:

  scala2:

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v7
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: init
      run: sbt -v --server update
      working-directory: ${{env.WORK_DIR}}
    - name: compile main
      run: sbt -v --server compile
      working-directory: ${{env.WORK_DIR}}
    - name: compile unit tests
      run: sbt -v --server 'Test / compile'
      working-directory: ${{env.WORK_DIR}}
    - name: formatting
      run: sbt -v --server scalafmtCheckAll
      working-directory: ${{env.WORK_DIR}}
    - name: tests
      run: sbt -v --server testFull
      working-directory: ${{env.WORK_DIR}}
    - name: coverage
      run: sbt -v --server xcoverage
      working-directory: ${{env.WORK_DIR}}
    - name: dependencies
      run: sbt -v --server dependencyTree dependencyUpdates
      working-directory: ${{env.WORK_DIR}}
    - name: assembly
      run: sbt -v --server assembly
      working-directory: ${{env.WORK_DIR}}

  project-template:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: create project template
      run: chmod u+x create-simple-project.sh && ./create-simple-project.sh
      working-directory: docs
