name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v13
      with:
        java-version: adopt@1.11
    - name: compile main
      run: sbt -v -Dfile.encoding=UTF-8 --client compile 
    - name: compile unit tests
      run: sbt -v -Dfile.encoding=UTF-8 --client test:compile
    - name: compile integration tests
      run: sbt -v -Dfile.encoding=UTF-8 --client it:compile
    - name: tests
      run: sbt -v -Dfile.encoding=UTF-8 --client test
    - name: assembly
      run: sbt -v -Dfile.encoding=UTF-8 --client assembly

  project-template:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v13
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: create project template
      run: cd docs && chmod u+x create-simple-project.sh && ./create-simple-project.sh
