name: Scala CI

on: [push]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: olafurpg/setup-scala@v13
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: sbt init
      run: sbt -v -Dfile.encoding=UTF-8 --client update 

  compile:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: olafurpg/setup-scala@v13
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: compile main
      run: sbt -v -Dfile.encoding=UTF-8 --client compile 

  testCompile:
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: olafurpg/setup-scala@v13
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: compile main
      run: sbt -v -Dfile.encoding=UTF-8 --client Test/compile

  intCompile:
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: olafurpg/setup-scala@v13
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: compile integration tests
      run: sbt -v -Dfile.encoding=UTF-8 --client IntegrationTest/compile

  test:
    runs-on: ubuntu-latest
    needs: [testCompile]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: olafurpg/setup-scala@v13
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: tests
      run: sbt -v -Dfile.encoding=UTF-8 --client test

  assembly:
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: olafurpg/setup-scala@v13
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: assembly
      run: sbt -v -Dfile.encoding=UTF-8 --client assembly

  project-template:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v13
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: create project template
      run: cd docs && chmod u+x create-simple-project.sh && ./create-simple-project.sh
