name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - name: Setup Scala and Java
      uses: olafurpg/setup-scala@v13
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: init
      run: sbt -v --client update 
    - name: compile main
      run: sbt -v --client compile 
    - name: compile unit tests
      run: sbt -v -Dfile.encoding=UTF-8 --client test:compile
    - name: compile integration tests
      run: sbt -v -Dfile.encoding=UTF-8 --client it:compile
    - name: tests
      run: sbt -v -Dfile.encoding=UTF-8 --client test
    - name: assembly
      run: sbt -v -Dfile.encoding=UTF-8 --client assembly

  project-template:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Setup Scala and Java
      uses: olafurpg/setup-scala@v13
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: create project template
      run: cd docs && chmod u+x create-simple-project.sh && ./create-simple-project.sh
